services:
  piszbot:
    build: .
    container_name: piszbot
    restart: unless-stopped
    env_file:
      - .env
    network_mode: "host"
    user: "1000:1000"  # 🆕 ДОБАВЬТЕ ЭТУ СТРОКУ
    environment:
      - DB_PATH=/app/data/applications.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./reports:/app/reports
      - /mnt/md3/servers/imagessmb/images:/mnt/images:ro
      - ./cache:/app/cache
