version: '3.8'

services:
  piszbot:
    build: .
    container_name: piszbot
    restart: unless-stopped
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - piszbot_data:/app/data
      - ./logs:/app/logs
      - ./reports:/app/reports
      # ✅ ДОБАВЬТЕ МОНТИРОВАНИЕ ДИРЕКТОРИИ С ИЗОБРАЖЕНИЯМИ
      - /mnt/md3/servers/imagessmb/images:/mnt/images:ro

volumes:
  piszbot_data: