sashap = ['Jellyfish Jam',
          'ABCdesign',
          'АВС дизайн'
          'Common Place',
          'Des Esseintes Press',
          'HylePress',
          'In Artibus',
          'K Gallery',
          'Kongress W press',
          'libra',
          'Libra Press',
          'MACHINA',
          'MOST',
          'No Kidding Press',
          'SOYAPRESS',
          'V-A-C press',
          'Авангард',
          'Аврора',
          'Азбуковник',
          'Академия исследования культуры',
          'Арт Волхонка',
          'Артист, режиссер, театр',
          'Арт-родник',
          'Белое яблоко',
          'БИО-пресс',
          'Борей Арт',
          'Б.С.Г.-ПРЕСС',
          'Галарт',
          'Галерея Наши художники',
          'Галеев Галерея',
          'Галерея печати',
          'Гангут',
          'ГИТИС',
          'ГМИИ им. А.С. Пушкина',
          'Государственный музей истории религии',
          'Гуманитарный центр',
          'ДЕАН',
          'Дитон',
          'Древности севера',
          'Европейский Дом',
          'Европейский университет в Санкт-Петербурге',
          'Журнал "Звезда"',
          'ИЗД.ДОМ РУДЕНЦОВЫХ',
          'Издательство Дединского',
          'Издательство Елены Терещенковой',
          'Издательство Ивана Лимбаха',
          'Изд-во им.НОВИКОВА',
          'Инкери',
          'Институт исследования и развития стрит-арта',
          'Институт общегуманитарных исследований (ИОИ)',
          'Историческая иллюстрация',
          'Каро',
          'Касталия',
          'Клаудберри',
          'Книжники',
          'Князев и Мисюк',
          'Коло',
          'КОНТАКТ-КУЛЬТУРА',
          'Красный пароход',
          'Крига',
          'Ладомир',
          'Летний сад',
          'ЛИК',
          'Лингва-Ф',
          'Магма',
          'Машина времени',
          'Медный Всадник',
          'Мир искусства',
          'Морское наследие',
          'Мосты культуры',
          'Музей русского импрессионизма'
          'Музей Фаберже',
          'Музыка',
          'Навона',
          'Найди лесоруба',
          'Невский ракурс',
          'Никея',
          'Н.Орiанда',
          'Новое литературное обозрение',
          'Остров',
          'Открытая кафедра',
          'Паритет',
          'Паулсен',
          'Прогресс-Традиция',
          'Прагмема',
          'Пропповский центр',
          'Редкая птица',
          'Реноме',
          'РИП-холдинг',
          'Роща',
          'Русский музей',
          'Свободные художники Петербурга',
          'Северный паломник',
          'Серебряный век',
          'Синдбад',
          'Сияние',
          'Скифия',
          'СОФИЯ',
          'София АНО',
          'СПбГУП',
          'терлецки комикс',
          'ТОНЧУ',
          'Третьяковская галерея',
          'Центр книги Рудомино',
          'Центр сохранения культурного наследия',
          'Циолковский',
          'Шанс',
          'Шрифт',
          'Шум',
          'Этерна',
          '4th Estate',
          '5 Continents edition',
          '66 book',
          'Abacus',
          'Abbeville Press',
          'Abrams books',
          'Academia',
          'Academie du Vin Librar',
          'ACC Distribution',
          'ACC-distribution titles',
          'Acta Diurna',
          'Actes Sud',
          'Albin Miche',
          'Algaida Literaria',
          'Alianza',
          'Alinar',
          'Alma Book',
          'Alma Classic',
          'Alma/Oneworld',
          'Amsterdam U',
          'ANACONDA',
          'Anaya ELE',
          'Antique Collectors Club Ltd',
          'Aperture',
          'Arnoi',
          'Arnoldsche Art',
          'Arrow Books',
          'Art Book',
          'Art Book Cologne',
          'Artisan',
          'Artmonsky Arts',
          'ArtPowe',
          'Ashmolean Museum',
          'Assouline',
          'Atlantic',
          'B De Bolsillo',
          'Batsford',
          'BBC Book',
          'Belveder',
          'Benteli Verlag',
          'Beta-plus',
          'Bijutsu Shuppansh',
          'Bis Publisher',
          'Black Dog publishing',
          'Black Swan',
          'Bloomsbury',
          'Booket',
          'Books & Project',
          'Bradt',
          'Braun Publishing',
          'British Museum',
          'California U',
          'Callwe',
          'Calmann-Levy',
          'Cameron Book',
          'Canongate',
          'Carlton Books Limited',
          'Catedra',
          'Centro Libr',
          'Cercle D`Art',
          'Cernunno',
          'CEU pres',
          'Chartwell Book',
          'Chelsea Green Publishin',
          'Chicago Review Pres',
          'Chiltern',
          'Cico Book',
          'COLLINS CLASSICS',
          'Columbia U',
          'Conran Octopus',
          'Cooking Lab',
          'Cooper Hewit',
          'Corrain',
          'Counter-Print',
          'Cronopio',
          'DAAB Media',
          'Damiani',
          'David & Charles',
          'CHRONICLE BOOKS',
          'David Zwirner',
          'DC Comic',
          'Debolsillo',
          'Del Rey',
          'DelMonico Book',
          'Design Museum Publishing',
          'Deutsche Guggenhei',
          'Dis Voi',
          'Dokumen',
          'Dominique Levy Galler',
          'Dorling Kindersley',
          'DOVER',
          'Drago',
          'dtv',
          'du Chene',
          'Duckworth',
          'Dumbrio Editora',
          'E/O',
          'Eakins Pres',
          'Editions Intervalles',
          'Editions Norm',
          'Egmont',
          'Einaudi',
          'Electa Architecture',
          'Esgotada',
          'Europa Editions',
          'FABER - CASTELL',
          'Faber & Faber',
          'Fallois',
          'Fantagraphic',
          'Fashionary',
          'Feltrinelli',
          'Fischer',
          'Fitzcarraldo Editions',
          'Flamant',
          'Flame Tree Publishing',
          'FLAMMARION',
          'Folio',
          'Forlagssystem',
          'Forma Edizioni',
          'Forum for Contemporary Art',
          'Frame',
          'Frances Lincoln',
          "FRANCES LINCOLN CHILDREN'S BOOKS",
          'Fuel',
          'Gadir Editoria',
          'Gagosian',
          'GALLIMARD',
          'Garzanti',
          'GESTALTEN',
          'Getty',
          'Giles',
          'Gingko Press',
          'GIUNTI DEMETRA',
          'Gollancz',
          'Granta Books',
          'GRASSET',
          'Greenfinch',
          'Guanda',
          'Guggenheim Museum',
          'Hachette Book Group',
          'Hachette Livre',
          'Hachette U',
          'Hachette UK',
          'Hannibal Publisher',
          'Hardie Grant Books',
          'HARPER',
          'Harper Collins USA',
          'HarperCollins Publishers',
          'HarperCollins UK',
          'HarperCollins USA',
          'Harvard  U',
          'HATJE CANTZ',
          'Headline',
          'Hirmer Verlag',
          'Hoaki',
          'Hodder & Stoughton Ltd.',
          'Hudson Hills Press',
          'Hutchinson',
          'IB Tauris',
          'Icon Book',
          'Idea book',
          'IMAGES PUBLISHING GROUP',
          'Impac',
          'Ingra',
          'Jacqui Small',
          "J'ai lu",
          'John Murray',
          'John Rul',
          'Jonathan Cape',
          'JouVence poch',
          'Jrp Ringier',
          'Karm',
          'Kehrer',
          'KiWi',
          'Knopf',
          'KONEMANN',
          'Kuperar',
          'Kyle Book',
          'L. King',
          'La Fabrica',
          'Langues pour tous',
          'Lannoo Books',
          'Lars Muller',
          'Laurence King Publishing Ltd',
          'LE LIVRE DE POCHE',
          'Lettera Ventidu',
          'Librio',
          'Little, Brown',
          'Livre de Poch',
          'Loft Publication',
          'Lonely Planet Publications Pty Ltd',
          'Ludion',
          'Lund Humphries',
          'MACK book',
          'MACMILLAN',
          "Macmillan Collector's Librar",
          'Magenta Publishin',
          'Manchester U',
          'Mark Batt',
          'Marsilio',
          'Merrell',
          'Metropolitan Museum of Art',
          'MFA Publications',
          'Minimum Fa',
          'Mitchell Beazley',
          'MODERN CLASSICS',
          'MoMA',
          'Monacelli Press',
          'Mondadori',
          'Monsa',
          'Munch Museum',
          'National Portrait Gallery Publications',
          'Niggli Verlag',
          'Norma Edition',
          'Norton',
          'Orion Books',
          'Orion Publishers',
          'Otav',
          'Oxford University Press',
          'Pallas Athen',
          'Pan Macmillan',
          'Park Book',
          'Parkett',
          'Paul Holberton Publishing',
          'Pegasu',
          'Penguin',
          'Penguin Books Ltd',
          'Penguin US',
          'Pepin Press',
          'Peter Pauper Pres',
          'PHAIDON',
          'Phaidon Press Ltd.',
          'Planet',
          'Pluto Pres',
          'POCKET',
          'Pointed Leaf Pres',
          'POLIGRAFA',
          'Ponte alle Grazi',
          'Prestel',
          'Prestel Publishing Limited',
          'PRH U',
          'PRH US',
          'Princeton Architectural Press',
          'Princeton UP',
          'PROFILE BOOKS',
          'Promopress',
          'Puffin Books',
          'Puffin U',
          'Pushkin Press',
          'Quadrille Publishin',
          'Quodlibet',
          'Random House',
          'Random House - Penguin',
          'Random House (USA)',
          'Random House US',
          'Reaktion books',
          'Rizzoli',
          'Rizzoli Internationa',
          'Routledge',
          'Royal Academy of Art',
          'ROYAL ACADEMY PUBLICATIONS',
          'Ryland Peters & Small',
          'Sandstein',
          'Scala',
          'Sceptre',
          'Scheidegger&Spiess',
          'Schiffer book',
          'SCHIRMER/MOSEL',
          'Scrib',
          'Scriptum Editions',
          'Sellerio',
          'SendPoint',
          'Signet',
          'Silvana',
          'Simon&Schuster UK',
          'SKIRA',
          'Smith Street',
          'Snoeck',
          'Sort of Book',
          'Soul Jazz Record',
          'Souvenir Pres',
          'Steidl',
          'Strandberg',
          'Suhrkam',
          'Tam Tam Book',
          'TASCHEN',
          'TATE PUBLISHING',
          'Teach Yoursel',
          'teNeues',
          'THAMES & HUDSON',
          'The American University in Cairo Pres',
          'The Borough Press',
          'The ME',
          'The World Diamond Museu',
          'Till Schaap Editio',
          'Titan books ltd.',
          'Toronto U',
          'Touring',
          'Twin Palms Publishers',
          'Unicorn pub',
          'Usborne',
          'V & A Publishing',
          'V&A',
          'Valiz',
          'Vendome Press',
          'Verso',
          'Vervuer',
          'VINTAGE',
          'Vintage books',
          'Virago',
          'VIRGIN BOOKS',
          'Vitra Design Museum',
          'Vivays Publishing',
          'VIZ Medi',
          'Viz Media',
          'Walther Konig',
          'Watchprin',
          'Wbooks',
          'Welbeck Publishing',
          'White Lion',
          'Whitechapel Art Galler',
          'Wordsworth Editions Limited',
          'Wordsworth Сlassics',
          'Workman',
          'Yale University Press',
          'Zed Book',
          'Zero book',
          'Zangavar',
          'Common Place',
          'Treemedia',
          'TATLIN',
          'Pollen press',
          'Jaromir Hladik press',
          'NAVONA',
          'Paulsen',
          'Smart Reading',
          'АВС дизайн',
          'Альтер Эго Бук',
          'Золотой лев',
          'Издательство Смена',
          'ИЗД-Я ГРУППА "NAVONA"',
          'Иностранная литература',
          'Киноартель 1895',
          'Носорог',
          'Сварог',
          'Смена',
          'Черный квадрат',
          'Чтиво',
          'Golden lion',
          'Издательство В. Шевчук',
          '4арт',
          'BETON',
          'BREUS',
          'Garage',
          'Hirmer Verlag',
          'Kerber',
          'Kerber Verla',
          'lutra',
          'Michael Imhof Verla',
          'Ozolnieki',
          'Palace Editions',
          'pop/off/art',
          'RA',
          'shell(f)',
          'Source',
          'Андрей Наследников',
          'Арт.Собрание',
          'АРТ-образ',
          'Архитектура-С',
          'Архэ',
          'Аякс-Пресс',
          'Бартлби и компания',
          'Винзавод',
          'ГАММА-ПРЕСС',
          'Гйоль',
          'ГМИ СПб',
          'Государственный институт искусствознания',
          'Гранат',
          'ДА',
          'Дефи',
          'Издательство "Да"',
          'Издательство Александр и Константин',
          'Издательство ПСТГУ',
          'Издательство СПбПДА',
          'Изд-во СБМ-ГАЛЕРЕЯ',
          'Карта Петра',
          'Киноведческие записки',
          'Клуб Касталия',
          'Красивые дома пресс',
          'Кузебай',
          'Лингвистика',
          'Марджани',
          'Мастерс',
          'МДА',
          'МДФ',
          'МОРКНИГА',
          'Музей русского импрессионизма',
          'Музей транспорта Москвы',
          'Музей Фаберже',
          'Напильник',
          'ОГИ',
          'П. Юргенсон',
          'Петербургский театральный журнал',
          'Пикторика',
          'Порт-Апрель',
          'Православный Свято-Тихоновский ГУ',
          'Пропилеи',
          'Радикальная теория и практика',
          'РуДа',
          'Рудомино',
          'Рутения',
          'Центр Зотов конструктивное пространство',
          'Эгалите']

tanya = ['Ad Marginem',
         'Chaosss/Press',
         'DOM Publishers',
         'Icebook',
         'Invalid Books',
         'Livebook',
         'Академический проект',
         'Альма Матер ИГ',
         'Арка',
         'Балтийские сезоны',
         'Барбарис',
         'ББИ',
         'Белый город',
         'Белый город. Воскресный день',
         'Библиороссика',
         'БуксМАрт',
         'Вече',
         'Водолей',
         'Выргород',
         'Высшая школа экономики',
         'Ганга',
         'Гиперион',
         'Гнозис',
         'Гонзо',
         'Деметра',
         'Дмитрий Буланин',
         'Еврейский музей',
         'Захаров',
         'Зебра Е',
         'Зело',
         'Издательство Студии Артемия Лебедева',
         'ИМЛИ РАН',
         'Искусство — XXI век',
         'Кабинетный ученый',
         'КЛАССИКА-XXI',
         'Книговек',
         'Колонна',
         'Культурная революция',
         'Кучково поле',
         'Кучково поле Музеон',
         'Лабиринт',
         'Лабиринт Пресс',
         'Лаборатория знаний',
         'Лимбус Пресс',
         'Логос',
         'Медленные книги',
         'Молодая гвардия',
         'Музей истории ГУЛАГа',
         'Нестор-История',
         'Новая газета',
         'Новое издательство',
         'Питер',
         'Пламень',
         'Посев',
         'Престиж Бук',
         'Принципиум',
         'Рама Паблишинг',
         'РГГУ',
         'РОССПЭН',
         'РОСФОТО',
         'СЛОВО/SLOVO',
         'Совпадение',
         'СПбГУ',
         'Страта',
         'Фантом Пресс',
         'Центрполиграф',
         'Коми республиканская типография',
         'Academic Studies Press',
         'Academic Studies Press/Библиороссика',
         'Kolonna publications',
         'Rosebud Publishing',
         'ЛомоносовЪ',
         'Митин журнал']

dusya = ['40 книг',
         'Topcreator Publishing',
         'Абрикобукс',
         'Август',
         'Август Борг',
         'Архипелаг',
         'Баобаб',
         'Белая ворона',
         'Бумкнига',
         'Волчок',
         'Графо',
         'Гудвин',
         'Детская литература',
         'Звонница-МГ',
         'Издательский проект "А и Б"',
         'Издательский Дом Мещерякова',
         'Карьера Пресс',
         'КомпасГид',
         'Лес рук',
         'Лимонад',
         'Лорета',
         'Лютература',
         'МАШИНЫ ТВОРЕНИЯ',
         'Мелик-Пашаев',
         'Миля',
         'Мозаика-Синтез',
         'Молодая мама',
         'Настя и Никита',
         'Нигма',
         'Образовательные проекты',
         'Октопус',
         'Омега',
         'Омега-Л',
         'Пешком в историю',
         'Поляндрия',
         'Поляндрия NoAge',
         'Попурри',
         'Речь',
         'Робинс',
         'Розовый жираф',
         'РОСМЭН',
         'Самокат',
         'Стрекоза',
         'ФЕНИКС',
         'Эрмит Парк',
         'Яуза',
         'Энас-книга',
         'ЭНАС',
         'Харди Гарди',
         'Фолиант',
         'Феникс, Ростов-на-Дону',
         'Улитка Коперника',
         'Полынь',
         'Морс',
         'ММ',
         'Место на полке',
         'Ламинария',
         'КОТОК',
         'Alpaca',
         'Badaboom',
         'Black Sheep Books',
         'Malamalama',
         'RADUGA GRЁZ',
         "Romana's book",
         'SENSE OF BEAUTY',
         'Абумба',
         'Банда умников',
         'Издательство "Rabbits and Books"',
         'Издательство 40 книг',
         'Издательство Молодая мама',
         'Клевер',
         'VoiceBook',
         '']

ev = ['Амфора',
      'Азбука',
      'Азбука-Бизнес',
      'БХВ-Петербург',
      'Вита Нова',
      'Детское время',
      'ПРОЗА И К',
      'ПРОЗАиК',
      'Иностранка',
      'КоЛибри',
      'Махаон',
      'Фонд "Дом детской книги"',
      'Книжный Клуб 36.6']

kirill = ['Bookwings',
          'Ibicus Press',
          'Nouveaux Angles',
          'PressPass',
          'Silene Noctiflora',
          'Агни',
          'Аграф',
          'АИРО-XXI',
          'Академия Русского балета им. А.Я.Вагановой',
          'Алетейя',
          'Алеф-Пресс',
          'Альпина',
          'БЛИЦ',
          'БММ АО',
          'Бослен',
          'Буддадхарма',
          'Военный музей Карельского перешейка',
          'Все свободны',
          'Городец',
          'Государственный литературный музей',
          'Гуманитарная академия',
          'Дилетант',
          'Директ-Медиа',
          'Дмитрий Сечин',
          'Из-во книжного магазина "Желтый двор"',
          'Издательство Азимут',
          'Издательский дом «Русская Философия»',
          'ИЗД.ДОМ ДЕЛО',
          'Индрик',
          'Инфра-М',
          'Искусство кино',
          'Канон+',
          'КУРС',
          'Лань',
          'Лики России',
          'Литературный институт имени А. М. Горького',
          'Литфакт',
          'Международные отношения',
          'Музей АЗ',
          'Мысль',
          'НАУКА',
          'Олимп-Бизнес',
          'Опустошитель',
          'Оренбургское книжное издательство',
          'Оренбургское книжное издательство имени Донковцева',
          'Петрополис',
          'Познание',
          'Проспект',
          'Р.Валент',
          'РГИСИ Изд-во',
          'Росток СПб',
          'Русская панорама',
          'Русский миръ',
          'Русский путь',
          'РХГА',
          'Свиньин и сыновья',
          'Сеанс',
          'Симпозиум',
          'Спорт-Марафон',
          'Три квадрата',
          'Умозрение',
          'Университет Дмитрия Пожарского',
          'Университетская книга',
          'Художественная литература',
          'Эксмо',
          'Элементарные формы',
          'Юрайт',
          'Комильфо',
          'XL Media',
          'Editions Nouveaux Angles',
          'Fanzon',
          'Popcorn books',
          'Individuum',
          'Inspiria',
          'АСТ',
          'Астрель',
          'Бомбора',
          'Вездец',
          'В. Секачев',
          'Дело',
          'Издательство редких  книг',
          'Изд-во Райхль',
          'Изд-во РГПУ им. А.И. Герцена',
          'Ласка-пресс',
          'Манн, Иванов и Фербер',
          'Одри',
          'Отто Райхль',
          'ПАЛЬМИР',
          'Пальмира',
          'RUGRAM_Пальмира',
          'Порядок слов',
          'Пятый Рим',
          'Рипол Классик',
          'Социум',
          'Т8 RUGRAM',
          'Планета музыки',
          'AZ музей',
          'Ruinaissance',
          'Zerde Publishing',
          'talweg',
          'Аронов',
          'Арт-Лайт',
          'БФУ им. И. Канта',
          'ГЦТМ им. А.А. Бахрушина',
          'Издат.проект "Quadrivium"',
          'Издательский проект "Quadrivium"',
          'Издательство Института Гайдара',
          'Издательство Композитор',
          'Издательство Олега Абышко',
          'ИРИСЭН',
          'Квадривиум',
          'Книжные мастерские',
          'Лениздат',
          'Музей театрального и музыкального искусства',
          'Родина',
          'Российский фонд содействия образованию и науке',
          'Русский фонд содействия образования и науки',
          'Серебряные нити',
          'ХлебСоль']

dima = ['Политехника']

yulya = ['Умная Бумага',
         'Умная Бумага',
         'Дворникова А.',
         'БумМагия',
         'Triggers',
         'SAKURA COLOR PRODUCTS CORPORATION',
         'Remarklee',
         'Red Wooden Flag',
         'Purpur',
         'PAPERBLANKS',
         'O PAPER PAPER',
         'Nuuna',
         'Noname brand',
         'MOLESKINE',
         'Leuchtturm1917',
         'Lanceplans',
         'LAMY',
         'Kateberrybookmarks',
         'Falafel',
         'ARTBOX']
